### ISSUE TITLE
Main-Section div content

### ISSUE THREAD

**Issue by moshechaikin** [moshechaikin/TAScience#1]
## Assigned to @YDixler 

Ignore the navbar for now, that needs some work (for later).

Here is a list of things I want you to do:

 - Create an `<hr>` tag directly under the `<h1>` tag that says Welcome
 - Create an empty div under that
 - Inside that div, create 3 buttons (make them each on a new line in the code so it's organized)
 - apply these classes to all of them btn btn-warning btn-lg ms-chapter-button 
 - Name the buttons 'Chapter 1', 'Chapter 2', and 'Chapter 3'
 - Do a git pull
 - git add
 - git commit -m "Message here" (please write the proper message describing what you did)
 - git push (Push it up there so I can see/get it) 

After you did all of this, please comment and say that you finished this, and close the issue.

**Comment by YDixler** [comment]
Done.
